# baseURL = "elm-ports.splode.co"
# languageCode = "en-us"
# title = ""
# theme = "journal"
# 
# [params]
#   description = "Supplemental information for a talk given at Elm Conf 2017 about Ports"
#   githubUsername = "splodingsocks"
#   twitterUsername = "splodingsocks"
#   tagline = "or: Using Ports for Good in the Real World."
# [params.work]
#   jobTitle = ""
#   company = "Day One"
#   companyUrl = "https://dayoneapp.com"
# [params.gpg]
#   key = "0x1111111111111111"
#   fingerprint = "0000 0000 0000 0000 0000  0000 0000 0000 0000 0000"
#   link = "https://pgp.mit.edu/pks/lookup?op=get&search=0x1111111111111111"
#   
  
baseurl = "https://example.org/"
languageCode = "en-us"
title = "A Very Im-port-ant Topic"
theme = "cactus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
disqusShortname = ""

[params]
	name = "Murphy Randle"
	description = ""
	bio = "Chief Smile Commander"
	# Enter optionally your twitter account
	twitter = "splodingsocks"
	enableRSS = false

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Chief Smile Commander at Day One"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/splodingsocks"
    github   = "https://www.github.com/splodingsocks"
